//! Low-level FFI bindings to the vendored [wslay](https://github.com/tatsuhiro-t/wslay)
//! WebSocket C library (MIT). Generated by bindgen at build time.
//!
//! This crate is unsafe FFI only; the safe, async wrapper lives in `h2ts-server`.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
